version: "3.8"

services:
  superbank-frontend:
    container_name: superbank-frontend
    build:
      context: ./superbank-frontend/
      dockerfile: Dockerfile
      target: final
    ports:
      - "3000:3000"
    depends_on:
      - superbank-backend

  superbank-backend:
    container_name: superbank-backend
    build:
      context: ./superbank-backend/
      dockerfile: Dockerfile
      target: final
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: superbank-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banks_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  pgdata:
    driver: local